apiVersion: v1
kind: Service
metadata:
  name: image-processor-function
  labels:
    app.kubernetes.io/name: image-processor-function
    app.kubernetes.io/part-of: web-socket
spec:
  selector:
    app.kubernetes.io/name: image-processor-function
    app.kubernetes.io/part-of: web-socket
  ports:
    - name: http
      port: 7071
      targetPort: http
